name: Build UI

on:
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo head to support automated local PRs
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - name: Checkout default if not upstream repo
        if: github.event.pull_request.head.repo.full_name != github.repository
        uses: actions/checkout@v4.1.1

      - id: check_label
        name: Check PL labels
        uses: docker://agilepathway/pull-request-label-checker:v1.6.21
        with:
          one_of: dependencies
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          allow_failure: true

      - name: Set up Node environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci
        working-directory: ui

      - name: Build and Copy
        run: npm run buildCopy
        working-directory: ui

      - name: Get Last Commit
        id: last_commit
        run: |
          echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=\"%an <%ae>\")" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.check_label.outputs.label_check == 'success'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: ${{ steps.last_commit.outputs.author }}
          commit_message: ${{ steps.last_commit.outputs.message }}
          commit_options: "--amend --no-edit"
          push_options: "--force"
          skip_fetch: true

      - name: Check static files uncommitted
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "There are uncommitted changes."
            git diff
            exit 1
          else
            echo "No uncommitted changes found."
          fi
