name: Test UI

on:
  pull_request:
    branches: [main]
    paths:
      - ui/*
      - .github/workflows/test-ui.yml
  push:
    branches: [main]
    paths:
      - ui/*
      - .github/workflows/test-ui.yml

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up Node environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci
        working-directory: ui

      - name: Run Vitest Tests
        run: npm run test:coverage
        working-directory: ui
